---
- name
- handle
- team
- initial stats
- num_caught
- km_walked
- battles_won
- magikarp_candy
- lure_modules
- eggs_hatched
- unique_pokemon
- pokemon_evolved
- comp_stats
- num_caught
- km_walked
- battles_won
- magikarp_candy
- lure_modules
- eggs_hatched
- unique_pokemon
- pokemon_evolved
---
- Lauren
- "--"
- Squirtle Squad
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
---
- Kenny
- "--"
- Pikachu Posse
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
---
- Joel
- "--"
- Charmander Club
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
---
- Patrick
- "--"
- Bulbasaur Bunch
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
---
- James
- "--"
- Pikachu Posse
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
- 
- '40'
- '26'
- '18'
- '83'
- '4'
- '6'
- '30'
- '4'
