default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gaslight-league_development

test:
  <<: *default
  database: gaslight-league_test

production:
  <<: *default
  database: gaslight-league_production
  adapter: postgresql
  encoding: unicode
  url:  <%= ENV["DATABASE_URL"] %>
